name: user_manager_domain
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  core_domain:
    git: 
      url: https://github.com/precastapp/core_module.git
      path: packages/core_domain
      ref: main

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
